repos:
  - repo: local
    hooks:
      - id: black
        name: black
        stages: [commit]
        language: system
        entry: pipenv run black
        types: [python]

      - id: flake8
        name: flake8
        stages: [commit]
        language: system
        entry: pipenv run flake8
        types: [python]
        exclude: setup.py

      - id: isort
        name: isort
        stages: [commit]
        language: system
        entry: pipenv run isort
        types: [python]

      - id: mypy
        name: mypy
        stages: [commit]
        language: system
        entry: pipenv run mypy
        types: [python]
        pass_filenames: false

      - id: pipfile-sort
        name: pipfile-sort
        stages: [commit]
        language: system
        entry: pipfile-sort
        pass_filenames: False
        file: Pipfile

      - id: pytest-cov
        name: pytest
        stages: [push]
        language: system
        entry: pipenv run pytest --cov --cov-fail-under=100
        types: [python]
        pass_filenames: false

      - id: gitlint
        name: gitlint
        stages: [commit-msg]
        language: system
        entry: gitlint
        types: [python]
        args:
          - "--staged"
          - "--msg-filename"
          - "--contrib"
