repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: check-builtin-literals
      args: ['--no-allow-dict-kwargs']
    - id: debug-statements
    # - id: double-quote-string-fixer
    - id: end-of-file-fixer
    - id: name-tests-test
    - id: sort-simple-yaml
    - id: trailing-whitespace
  # - repo: https://github.com/asottile/reorder_python_imports
  #   rev: v1.6.1
  #   hooks:
  #   - id: reorder-python-imports
  #     language_version: python3
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v1.4.1
    hooks:
    - id: add-trailing-comma
  - repo: local
    hooks:
      - id: black
        name: black
        stages: [commit]
        language: system
        entry: pipenv run black
        types: [python]

      - id: detect-secrets
        name: Detect secrets
        description: Detects high entropy strings that are likely to be passwords.
        entry: detect-secrets-hook
        language: python
        args: ['--baseline', '.secrets.baseline']

      - id: flake8
        name: flake8
        stages: [commit]
        language: system
        entry: pipenv run flake8
        types: [python]
        exclude: setup.py

      - id: isort
        name: isort
        stages: [commit]
        language: system
        entry: pipenv run isort
        types: [python]

      - id: mypy
        name: mypy
        stages: [commit]
        language: system
        entry: pipenv run mypy
        types: [python]
        pass_filenames: false

      - id: pipfile-sort
        name: pipfile-sort
        stages: [commit]
        language: system
        entry: pipfile-sort
        pass_filenames: False
        files: Pipfile

      - id: pytest-cov
        name: pytest
        stages: [push]
        language: system
        entry: pipenv run pytest --cov --cov-fail-under=100
        types: [python]
        pass_filenames: false

      - id: gitlint
        name: gitlint
        stages: [commit-msg]
        language: system
        entry: gitlint
        types: [python]
        args:
          - "--staged"
          - "--msg-filename"
          - "--contrib"
