language: python
python:
  - "3.9"
services:
  - docker
addons:
  sonarcloud:
    organization: "gotreasa" # the key of the org you chose at step #3
before_install:
- pip install poetry==1.1.13
install:
- poetry install
stages:
- name: Quality checks
- name: Test
jobs:
  include:
  - stage: Quality Checks
    env: step=Snyk vulnerability check
    name: Snyk vulnerability check
    script:
      poetry run task test:security
  - env: step=Detect secrets in files
    name: Detect secrets in files
    script:
      - detect-secrets scan
  - stage: Test
    env: step=Run tests and Sonar Scanner
    name: Run tests and Sonar Scanner
    script:
      - poetry run task test
      - sonar-scanner -Dproject.settings=sonar-project.propoerties
